package app.hushmessenger.extension;

/** Traditional Chinese (Taiwan) translation for all shipped HushMessenger settings text. */
final class SettingsTextZhTw {
    private SettingsTextZhTw() { }

    static final String[][] TEXT = {
        {"controls", "控制項"},
        {"app", "應用程式"},
        {"all", "全部"},
        {"inbox", "收件匣"},
        {"chats", "聊天"},
        {"more", "其他"},
        {"navigation", "導覽"},
        {"stickers", "貼圖"},
        {"conversations", "對話"},
        {"links_bubbles", "連結與聊天泡泡"},
        {"privacy", "隱私"},
        {"theme", "主題"},
        {"settings", "HushMessenger 設定"},
        {"preview_title", "HushMessenger 介面預覽"},
        {"preview_notice", "介面預覽。這些開關不會修改 Messenger。"},
        {"tagline", "讓 Messenger 更符合你的使用方式。"},
        {"open", "開啟"},
        {"open_messenger", "開啟 Messenger"},
        {"reopen", "收件匣變更會在「應用程式」>「重新啟動 Messenger」後套用。"},
        {"quick_access", "快速操作"},
        {"access_help", "長按主畫面的 Messenger 圖示可使用「Patch 控制」或「重新啟動 Messenger」。你也可以從應用程式清單開啟 HushMessenger 設定。"},
        {"hide_drawer_icon", "隱藏應用程式清單圖示"},
        {"hide_drawer_icon_help", "從應用程式清單移除 HushMessenger 設定圖示。仍可從 Messenger 的「選單」分頁或側邊選單開啟，或長按主畫面的 Messenger 圖示並點選「Patch 控制」。"},
        {"shared_install_help", "設定圖示屬於 Messenger。解除安裝任一圖示都會移除 Messenger 與其本機資料。若只想隱藏此入口，請使用「隱藏應用程式清單圖示」。"},
        {"access_help_hosted", "長按主畫面的 Messenger 圖示可使用「Patch 控制」或「重新啟動 Messenger」。Root Mount 安裝不會在應用程式清單中建立獨立設定圖示。"},
        {"access_help_hosted_menu", "長按主畫面的 Messenger 圖示可使用「Patch 控制」或「重新啟動 Messenger」，也可從 Messenger「選單」分頁或側邊選單中的 HushMessenger 入口開啟設定。Root Mount 安裝不會在應用程式清單中建立獨立設定圖示。"},
        {"access_help_menu", "長按主畫面的 Messenger 圖示可使用「Patch 控制」或「重新啟動 Messenger」。你也可以從 Messenger「選單」分頁或側邊選單中的 HushMessenger 入口，或從應用程式清單開啟設定。"},
        {"access_help_missing", "長按主畫面的 Messenger 圖示可使用「Patch 控制」或「重新啟動 Messenger」。此核心未提供應用程式清單中的設定圖示。"},
        {"access_help_missing_menu", "可從 Messenger 的「選單」分頁或側邊選單開啟 HushMessenger，或長按主畫面的 Messenger 圖示使用「Patch 控制」或「重新啟動 Messenger」。此核心未提供應用程式清單中的設定圖示。"},
        {"drawer_search", "應用程式清單圖示設定"},
        {"drawer_root", "Root Mount 不需要「隱藏應用程式清單圖示」，因為沒有獨立設定圖示可隱藏。"},
        {"drawer_missing", "此核心沒有設定啟動器別名，因此無法隱藏應用程式清單圖示。"},
        {"drawer_requires_menu", "「隱藏應用程式清單圖示」需要 Messenger「選單」分頁或側邊選單中的 HushMessenger 入口。當快捷方式是唯一其他入口時，圖示會保持可用。"},
        {"restart", "重新啟動 Messenger"},
        {"restarting", "正在重新啟動 Messenger…"},
        {"restart_unavailable", "無法重新啟動。請關閉 Messenger，再從應用程式清單重新開啟。"},
        {"settings_open_failed", "無法開啟 HushMessenger 設定。請長按主畫面的 Messenger 圖示，再嘗試「Patch 控制」。"},
        {"restart_save_failed", "無法儲存選擇，因此沒有重新啟動 Messenger。請再試一次。"},
        {"setup", "目前設定"},
        {"paused", "暫停所有變更"},
        {"search", "尋找控制項"},
        {"empty_title", "尋找需要的控制項"},
        {"empty_help", "請改用其他搜尋字詞或分類。這裡只會顯示本次安裝包含的補丁。"},
        {"clear", "清除篩選"},
        {"unavailable", "此 Android 版本無法使用。你的選擇會保留。"},
        {"bubble_stock", "原始模式"},
        {"bubble_chat_heads", "Chat Heads"},
        {"bubble_native", "原生泡泡"},
        {"bubble_changed", "已選擇 %s。請重新啟動 Messenger 以套用。"},
        {"bubble_help", "「原始模式」交由 Messenger 自行決定。「Chat Heads」還需要開啟 Messenger 的 Chat heads 開關與懸浮顯示權限。「原生泡泡」請使用下方 Android 泡泡設定允許 Messenger 泡泡；仍需通知權限與帳號支援。不支援的帳號會維持 Messenger 原本流程。「暫停所有變更」會恢復原始模式。"},
        {"bubble_unsupported", "此核心沒有已驗證的原生泡泡路徑。Messenger 會維持原始行為，你儲存的選擇仍會保留。"},
        {"bubble_permissions", "Android 泡泡設定"},
        {"bubble_notifications", "Messenger 通知設定"},
        {"bubble_conversations", "Android 對話設定"},
        {"bubble_settings_missing", "此手機沒有相符的設定頁。請開啟 Messenger 的應用程式資訊，再進入「通知」。"},
        {"experimental", "實驗性"},
        {"choice_on", "%s：開啟"},
        {"choice_off", "%s：關閉"},
        {"appearance", "外觀"},
        {"light", "淺色主題"},
        {"light_help", "在設定頁使用淺色背景。"},
        {"theme_help", "預設使用深色主題。你的選擇會儲存。"},
        {"about", "關於 HUSHMESSENGER"},
        {"version", "版本"},
        {"installed", "已安裝控制項"},
        {"copy", "複製設定"},
        {"copy_help", "複製應用程式版本與控制項選擇。不包含帳號或聊天內容，也不會傳送任何資料。"},
        {"usage", "使用控制項"},
        {"save_help", "變更會自動儲存。修改收件匣控制項後，請使用「重新啟動 Messenger」。帳號會保持登入。"},
        {"pause_help", "暫停會保留你的選擇，並暫時恢復原始行為。"},
        {"account_help", "你的選擇會套用到此安裝中的所有 Messenger 帳號。"},
        {"missing", "找不到控制項？"},
        {"missing_help", "請在 Nivqo Manager 選取後重新建置 Messenger。只更新來源不會安裝新的控制項。"},
        {"source", "來源與授權"},
        {"no_browser", "沒有可用的瀏覽器"},
        {"credits", "GPL-3.0。包含 De-Vanced、ReVanced、Doom 與 Messenger Cleaner 的工作。"},
        {"independent", "獨立於 Meta 與 Morphe。"},
        {"clipboard", "HushMessenger 設定"},
        {"copied", "設定已複製"},
        {"copy_failed", "無法複製設定。請再試一次。"},
        {"export", "匯出選擇"},
        {"export_help", "將控制項選擇複製到剪貼簿。貼到另一個安裝的「匯入選擇」即可還原。"},
        {"exported", "選擇已匯出"},
        {"export_failed", "無法匯出。請再試一次。"},
        {"import_choices", "匯入選擇"},
        {"import_help", "從剪貼簿讀取選擇。請先複製一份匯出內容。"},
        {"imported_one", "已還原 %d 個選擇"},
        {"imported_many", "已還原 %d 個選擇"},
        {"import_empty", "沒有可匯入的內容。請先匯出選擇，再貼到這裡。"},
        {"import_invalid", "這不是有效的 HushMessenger 備份。請使用未修改且不超過 16 KiB 的選擇匯出檔。"},
        {"import_unknown_one", "已略過 %d 個未知選擇。"},
        {"import_unknown_many", "已略過 %d 個未知選擇。"},
        {"import_unavailable_one", "已略過此核心未包含的 %d 個選擇。"},
        {"import_unavailable_many", "已略過此核心未包含的 %d 個選擇。"},
        {"import_no_choices", "沒有已安裝的控制項選擇可還原。"},
        {"save_choices_file", "將選擇儲存到檔案"},
        {"read_choices_file", "從檔案還原選擇"},
        {"choices_file_help", "僅包含設定，最多 16 KiB；不包含聊天、帳號或復原資料。未列出或不可用的選擇會保留目前儲存值。若設定頁重新開啟，請重新選取檔案。"},
        {"choices_file_saved", "選擇檔案已儲存"},
        {"choices_file_saving", "正在儲存選擇檔案…"},
        {"choices_file_reading", "正在讀取選擇檔案…"},
        {"choices_file_changed", "讀取檔案期間選擇已變更。若要以檔案內容取代，請再次還原該檔案。"},
        {"check_updates", "檢查更新"},
        {"check_updates_help", "啟用時或開啟設定頁時會向 GitHub 檢查更新。預設關閉。GitHub 會收到你的 IP 位址與連線中繼資料；不會上傳帳號或聊天內容。"},
        {"check_now", "立即檢查"},
        {"update_loading", "正在檢查更新…"},
        {"update_available", "已有版本 %s 可用"},
        {"update_action", "查看版本"},
        {"up_to_date", "目前已是最新版本。"},
        {"update_error", "無法檢查更新。"},
        {"active_now", "剛剛使用"},
        {"active_ago", "%s 前使用"},
        {"seconds_short", "%d 秒"},
        {"minutes_short", "%d 分鐘"},
        {"hours_short", "%d 小時"},
        {"not_active", "重新啟動後尚無可變更項目"},
        {"unsent_not_active", "重新啟動後尚未偵測到收回訊息活動"},
        {"error_now", "剛剛因錯誤停止"},
        {"error_ago", "%s 前因錯誤停止"},
        {"changes_paused", "變更已暫停"},
        {"changes_resumed", "已恢復變更"},
        {"safe_mode", "安全模式"},
        {"safe_mode_help", "Messenger 連續多次當機，因此所有控制項已關閉。你的選擇仍會保留；點選「恢復」即可重新啟用。"},
        {"safe_mode_help_paused", "Messenger 連續多次當機。你的選擇仍已儲存；請先清除安全模式。「暫停所有變更」會保持開啟，直到你手動關閉。"},
        {"resume", "恢復"},
        {"clear_safe_mode", "清除安全模式"},
        {"safe_mode_cleared", "安全模式已清除，變更仍維持暫停。"},
        {"enabled_one", "已啟用 %d 個控制項"},
        {"enabled_many", "已啟用 %d 個控制項"},
        {"saved_one", "已儲存 %d 個選擇。關閉暫停即可恢復。"},
        {"saved_many", "已儲存 %d 個選擇。關閉暫停即可恢復。"},
        {"saved", "你的選擇會自動儲存。"},
        {"none_installed", "尚未安裝選用控制項。請在 Nivqo Manager 選取補丁並重新建置 Messenger。"},
        {"no_matches", "找不到符合的控制項。請換個搜尋字詞。"},
        {"results_one", "已安裝控制項：%d / %d"},
        {"results_many", "已安裝控制項：%d / %d"},
        {"open_help", "從應用程式清單開啟 Messenger"},
        {"language", "語言"},
        {"choose_language", "選擇"},
        {"apply", "套用"},
        {"cancel", "取消"},
        {"language_system", "跟隨系統"},
        {"language_zh_tw", "繁體中文"},
        {"language_en", "English"},
        {"language_help", "選擇 HushMessenger 使用的語言，可選「跟隨系統」、「繁體中文」或 English。"},
        {"ads.title", "隱藏收件匣廣告"},
        {"ads.description", "如果 Meta 重新啟用 2025 年 11 月停止販售的收件匣廣告，便移除這些廣告卡片。"},
        {"people.title", "隱藏「你可能認識的人」"},
        {"people.description", "從聊天、搜尋、限時動態，以及「聯絡人」與通知分頁移除好友建議。"},
        {"friend_requests.title", "隱藏交友邀請卡片"},
        {"friend_requests.description", "隱藏交友邀請卡片，不會接受或拒絕邀請。"},
        {"growth.title", "隱藏成長推廣提示"},
        {"growth.description", "移除收件匣中邀請加入更多聯絡人的提示，也隱藏便利貼中的提示面板（例如「公開我的便利貼」）與看完他人限時動態後的「分享你自己的限時動態」卡片。"},
        {"inbox_promotions.title", "隱藏收件匣推廣"},
        {"inbox_promotions.description", "隱藏聊天列表中的 Messenger 快速推廣橫幅。"},
        {"stories.title", "隱藏限時動態與便利貼"},
        {"stories.description", "移除聊天上方的橫向列。"},
        {"subtabs.title", "隱藏收件匣分頁"},
        {"subtabs.description", "隱藏收件匣中的首頁與頻道分頁。"},
        {"facebook.title", "隱藏 Facebook 捷徑"},
        {"facebook.description", "隱藏 Facebook 按鈕、個人檔案與分享捷徑，以及「選單」分頁中的「Also from Meta」。"},
        {"meta_ai.title", "隱藏 Meta AI"},
        {"meta_ai.description", "隱藏浮動按鈕、工具列按鈕、Meta AI 分頁、選單項目與搜尋中的 AI。"},
        {"moments.title", "隱藏 Chat Moments"},
        {"moments.description", "隱藏選單中的 Chat Moments。"},
        {"reels_badge.title", "隱藏 Reels 徽章"},
        {"reels_badge.description", "隱藏 Reels 通知徽章。"},
        {"chat_animation.title", "聊天滑入滑出動畫"},
        {"chat_animation.description", "從聊天列表或搜尋開啟聊天時，讓聊天畫面從側邊滑入；返回時滑出，底下畫面保持不動。Chat Heads 與泡泡會保留自己的動畫。"},
        {"ai_stickers.title", "隱藏 AI 貼圖工具"},
        {"ai_stickers.description", "隱藏產生貼圖分頁與 AI 貼圖建議。"},
        {"avatar_stickers.title", "隱藏虛擬替身貼圖"},
        {"avatar_stickers.description", "隱藏貼圖鍵盤中的虛擬替身分頁。"},
        {"chat_promotions.title", "隱藏聊天推廣"},
        {"chat_promotions.description", "隱藏對話中的 Messenger 快速推廣橫幅。"},
        {"suggested_replies.title", "隱藏商家回覆建議"},
        {"suggested_replies.description", "隱藏商家對話中的建議回覆。"},
        {"business_suggestions.title", "隱藏商家輸入建議"},
        {"business_suggestions.description", "輸入文字時隱藏商家相關建議。"},
        {"event_prompts.title", "隱藏活動提示"},
        {"event_prompts.description", "隱藏聊天中的活動快速推廣提示。"},
        {"typing.title", "隱藏輸入中狀態"},
        {"typing.description", "停止傳送你的「正在輸入」狀態，包括端對端加密聊天。"},
        {"use_system_emoji.title", "使用系統 Emoji"},
        {"use_system_emoji.description", "使用手機自己的 Emoji 字型，而不是 Messenger 內建的 Emoji。"},
        {"original_photo.title", "以原始畫質傳送照片"},
        {"original_photo.description", "開啟 HD 時，直接傳送 JPEG 照片本身的影像資料，不使用 Messenger 重新編碼的版本。位置、相機資訊等中繼資料仍會移除，只保留讓橫向照片正確旋轉的標記。超過 20 MB 的照片與影片仍會由 Messenger 壓縮。"},
        {"external_browser.title", "使用外部瀏覽器開啟網頁連結"},
        {"external_browser.description", "HTTP 與 HTTPS 連結使用預設瀏覽器；其他連結維持原本行為。"},
        {"bubbles.title", "允許聊天泡泡"},
        {"bubbles.description", "選擇原始模式、Chat Heads 或原生泡泡。原生泡泡需要 Android 11、帳號支援與通知權限；變更模式後請重新啟動 Messenger。"},
        {"allow_screenshot.title", "允許截圖"},
        {"allow_screenshot.description", "允許截取 Messenger 在聊天中保護的照片、媒體與影片，並停止截圖通知。僅限查看一次的媒體仍受保護。"},
        {"hide_read_receipts.title", "隱藏已讀回條"},
        {"hide_read_receipts.description", "停止傳送已讀回條。已開啟的端對端加密聊天在此手機上可能維持未讀；回覆訊息或關閉此功能可能會通知對方。群組聊天支援尚未驗證。"},
        {"keep_unsent.title", "保留已收回訊息"},
        {"keep_unsent.description", "在已驗證的舊式收回訊息路徑保留被收回的訊息。不支援端對端加密聊天，群組聊天支援尚未驗證。活動紀錄代表攔截到舊式收回事件，不代表該聊天一定受支援；啟用時你自己的收回功能可能受限。"},
        {"anonymous_stories.title", "匿名觀看限時動態"},
        {"anonymous_stories.description", "開啟其他人的限時動態時，不會把你加入對方的觀看名單；在你這一端仍會標記為已看。"},
        {"save_stories.title", "儲存任何限時動態"},
        {"save_stories.description", "在其他人的限時動態「更多」選單加入「儲存」。相片或影片會使用 Messenger 原本儲存自己限時動態的方式存到手機。"},
        {"material_you.title", "Material You 主題"},
        {"material_you.description", "Android 12 以上讓 Messenger 深色模式使用桌布配色；Android 11 使用固定藍色調。淺色模式不變。請先在 Messenger 開啟深色模式。"},
    };
}
